import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "fr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.services": "Services",
    "nav.solutions": "Solutions",
    "nav.features": "Fonctionnalités",
    "nav.contact": "Contact",
    "nav.login": "Connexion",
    "nav.start": "Commencer",
    "nav.dashboard": "Mon Espace",
    
    // Hero
    "hero.title1": "Votre",
    "hero.title2": "Archiviste",
    "hero.title3": "Intelligent",
    "hero.description": "De votre poche à la Nation — La première plateforme d'archivage intelligent multi-échelle. Numérisez, organisez et sécurisez vos documents avec l'IA.",
    "hero.cta.primary": "Essayer Gratuitement",
    "hero.cta.secondary": "Voir la Démo",
    
    // Services
    "services.title1": "Des Solutions",
    "services.title2": "Complètes",
    "services.description": "DIGITALIUM transforme la gestion documentaire du citoyen à l'institution.",
    "services.scan.title": "Scan Intelligent",
    "services.scan.description": "Numérisez vos documents avec notre technologie OCR avancée.",
    "services.ai.title": "Assistant IA",
    "services.ai.description": "Un archiviste intelligent disponible 24/7.",
    "services.security.title": "Sécurité Souveraine",
    "services.security.description": "Chiffrement de niveau bancaire, hébergement local.",
    "services.persona.title": "Multi-Persona",
    "services.persona.description": "Interface adaptée à chaque profil utilisateur.",
    "services.offline.title": "Mode Offline",
    "services.offline.description": "Travaillez sans connexion, sync automatique.",
    "services.workflow.title": "Workflows",
    "services.workflow.description": "Automatisez vos processus documentaires.",
    "services.learnMore": "En savoir plus",
    "services.cta": "Découvrir tous nos services",
    
    // Solutions
    "solutions.title1": "Une Solution",
    "solutions.title2": "Adaptée",
    "solutions.description": "Du particulier à l'administration publique, DIGITALIUM s'adapte à votre échelle.",
    "solutions.popular": "Plus populaire",
    "solutions.choose": "Choisir",
    "solutions.citizen.title": "Citoyens",
    "solutions.citizen.subtitle": "DIGITALIUM Personnel",
    "solutions.citizen.description": "Organisez tous vos documents administratifs simplement.",
    "solutions.citizen.price": "Gratuit",
    "solutions.citizen.f1": "CNI, passeport, diplômes",
    "solutions.citizen.f2": "Rappels d'expiration",
    "solutions.citizen.f3": "100 docs gratuits",
    "solutions.business.title": "Entreprises",
    "solutions.business.subtitle": "DIGITALIUM Business",
    "solutions.business.description": "Digitalisez votre gestion documentaire.",
    "solutions.business.price": "15 000 XAF/mois",
    "solutions.business.f1": "Multi-utilisateurs",
    "solutions.business.f2": "Workflows automatisés",
    "solutions.business.f3": "API & Intégrations",
    "solutions.institution.title": "Institutions",
    "solutions.institution.subtitle": "DIGITALIUM Souverain",
    "solutions.institution.description": "Solution souveraine pour les administrations.",
    "solutions.institution.price": "Sur devis",
    "solutions.institution.f1": "Hébergement Gabon",
    "solutions.institution.f2": "Support 24/7",
    "solutions.institution.f3": "Formation incluse",
    "solutions.trust": "Ils nous font confiance",
    
    // Features
    "features.title1": "L'IA qui",
    "features.title2": "Travaille",
    "features.title3": "pour Vous",
    "features.description": "Une expérience de gestion documentaire fluide et intuitive.",
    "features.assistant.title": "Assistant IA",
    "features.assistant.description": "Parlez naturellement à votre archiviste IA pour organiser vos documents.",
    "features.scan.title": "Scan Intelligent",
    "features.scan.description": "Numérisez avec votre smartphone, l'IA extrait automatiquement le texte.",
    "features.organization.title": "Organisation Auto",
    "features.organization.description": "L'IA classe automatiquement vos documents par catégorie et date.",
    "features.alerts.title": "Alertes Intelligentes",
    "features.alerts.description": "Soyez prévenu avant l'expiration de vos documents importants.",
    "features.share.title": "Partage Sécurisé",
    "features.share.description": "Partagez des documents avec contrôle total des permissions.",
    "features.encryption.title": "Chiffrement E2E",
    "features.encryption.description": "Vos documents sensibles chiffrés, même nous ne pouvons les lire.",
    "features.demo.title": "Voyez l'IA en Action",
    "features.demo.request": "Prépare un dossier pour ma demande de visa France",
    "features.demo.response": "J'ai trouvé 5 documents dans vos archives. Je crée le dossier 'Visa France 2024' avec : passeport, relevés bancaires (3 derniers mois), attestation employeur...",
    
    // Contact
    "contact.title1": "Parlons de Votre",
    "contact.title2": "Projet",
    "contact.description": "Notre équipe est disponible pour répondre à toutes vos questions et vous accompagner dans votre transformation digitale.",
    "contact.address": "Adresse",
    "contact.address.value": "Libreville, Gabon",
    "contact.phone": "Téléphone",
    "contact.phone.value": "+241 XX XX XX XX",
    "contact.email": "Email",
    "contact.email.value": "contact@digitalium.ga",
    "contact.hours": "Horaires",
    "contact.hours.value": "Lun-Ven : 8h-18h",
    "contact.form.name": "Votre nom *",
    "contact.form.email": "Votre email *",
    "contact.form.subject": "Sujet",
    "contact.form.message": "Votre message *",
    "contact.form.submit": "Envoyer le message",
    "contact.form.sending": "Envoi en cours...",
    "contact.form.success.title": "Message Envoyé !",
    "contact.form.success.description": "Notre équipe vous répondra sous 24h.",
    "contact.form.new": "Envoyer un nouveau message",
    "contact.form.required": "Champs requis",
    "contact.form.required.description": "Veuillez remplir tous les champs obligatoires.",
    "contact.form.error": "Erreur",
    "contact.form.error.description": "Une erreur est survenue. Veuillez réessayer.",
    "contact.map": "Carte",
    "contact.callNow": "Appelez-nous maintenant",
    
    // FAQ
    "faq.badge": "FAQ",
    "faq.title1": "Questions",
    "faq.title2": "Fréquentes",
    "faq.description": "Tout ce que vous devez savoir sur DIGITALIUM et comment il peut transformer votre gestion documentaire.",
    "faq.more": "Vous avez d'autres questions ?",
    "faq.contact": "Contactez notre équipe",
    "faq.q1": "Qu'est-ce que DIGITALIUM et comment fonctionne-t-il ?",
    "faq.a1": "DIGITALIUM est la première plateforme d'archivage intelligent multi-échelle qui combine IA générative et rigueur institutionnelle. Notre assistant archiviste analyse automatiquement vos documents, les classe, extrait les métadonnées et vous aide à les retrouver instantanément grâce à une recherche sémantique avancée.",
    "faq.q2": "Mes documents sont-ils sécurisés sur DIGITALIUM ?",
    "faq.a2": "Absolument. Nous utilisons un chiffrement AES-256 pour les données au repos et TLS 1.3 pour les données en transit. Pour les institutions, nous proposons une option de chiffrement de bout en bout avec hébergement souverain au Gabon. Toutes les actions sont tracées dans un journal d'audit immutable.",
    "faq.q3": "Quels types de documents puis-je scanner et archiver ?",
    "faq.a3": "DIGITALIUM accepte tous types de documents : CNI, passeports, diplômes, factures, contrats, actes notariés, relevés bancaires, certificats médicaux, et bien plus. Notre IA détecte automatiquement le type de document et l'organise dans la bonne catégorie.",
    "faq.q4": "Puis-je utiliser DIGITALIUM hors ligne ?",
    "faq.a4": "Oui ! DIGITALIUM fonctionne en mode offline-first. Vous pouvez scanner, organiser et consulter vos documents même sans connexion internet. Tout se synchronise automatiquement dès que vous retrouvez une connexion.",
    "faq.q5": "Comment fonctionne la tarification ?",
    "faq.a5": "Nous proposons une offre gratuite avec 1 Go de stockage et 100 documents. L'offre Personal à 2 000 XAF/mois inclut 10 Go et documents illimités. L'offre Family à 5 000 XAF/mois permet jusqu'à 5 utilisateurs. Pour les entreprises et institutions, contactez-nous pour un devis personnalisé.",
    "faq.q6": "L'IA peut-elle vraiment comprendre mes documents ?",
    "faq.a6": "Oui, notre IA utilise des modèles de dernière génération pour analyser visuellement et textuellement vos documents. Elle peut extraire des données structurées (dates, montants, noms), détecter les documents expirés, et même vous suggérer des actions comme la création de dossiers thématiques.",
    "faq.q7": "Comment DIGITALIUM aide les entreprises ?",
    "faq.a7": "Pour les entreprises, DIGITALIUM offre des workflows automatisés (validation de factures, onboarding employés), la gestion multi-utilisateurs avec RBAC, des tableaux de bord analytiques, l'intégration API, et des rapports de conformité. Le ROI moyen constaté est de 253% avec un temps de retour sur investissement de 15 jours.",
    "faq.q8": "DIGITALIUM est-il disponible pour les administrations publiques ?",
    "faq.a8": "Oui, nous proposons une offre Institutional spécialement conçue pour les mairies, ministères et administrations. Elle inclut le déploiement on-premise, l'hébergement souverain au Gabon, la conformité RGPD et loi gabonaise, ainsi qu'un support dédié 24/7.",
    
    // Footer
    "footer.description": "L'archiviste intelligent qui transforme votre gestion documentaire. Made in Gabon 🇬🇦",
    "footer.copyright": "Tous droits réservés.",
    "footer.poweredBy": "Propulsé par",
    "footer.product": "Produit",
    "footer.product.features": "Fonctionnalités",
    "footer.product.solutions": "Solutions",
    "footer.product.pricing": "Tarifs",
    "footer.product.security": "Sécurité",
    "footer.company": "Entreprise",
    "footer.company.about": "À propos",
    "footer.company.careers": "Carrières",
    "footer.company.partners": "Partenaires",
    "footer.company.blog": "Blog",
    "footer.resources": "Ressources",
    "footer.resources.docs": "Documentation",
    "footer.resources.api": "API",
    "footer.resources.support": "Support",
    "footer.resources.status": "Statut",
    "footer.legal": "Légal",
    "footer.legal.privacy": "Confidentialité",
    "footer.legal.terms": "CGU",
    "footer.legal.cookies": "Cookies",
    "footer.legal.licenses": "Licences",
    
    // Auth
    "auth.title": "DIGITALIUM",
    "auth.subtitle": "Accédez à votre espace personnel",
    "auth.login": "Connexion",
    "auth.signup": "Inscription",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.confirmPassword": "Confirmer le mot de passe",
    "auth.fullName": "Nom complet",
    "auth.emailPlaceholder": "vous@exemple.com",
    "auth.passwordPlaceholder": "••••••••",
    "auth.namePlaceholder": "Jean Dupont",
    "auth.loginButton": "Se connecter",
    "auth.signupButton": "Créer un compte",
    "auth.logging": "Connexion...",
    "auth.creating": "Création...",
    "auth.loginError": "Erreur de connexion",
    "auth.loginErrorMsg": "Email ou mot de passe incorrect.",
    "auth.error": "Erreur",
    "auth.accountExists": "Compte existant",
    "auth.accountExistsMsg": "Un compte existe déjà avec cet email. Connectez-vous plutôt.",
    "auth.signupError": "Erreur d'inscription",
    "auth.loginSuccess": "Connexion réussie",
    "auth.loginSuccessMsg": "Bienvenue sur DIGITALIUM !",
    "auth.signupSuccess": "Compte créé !",
    "auth.signupSuccessMsg": "Bienvenue sur DIGITALIUM !",
    "auth.invalidEmail": "Email invalide",
    "auth.passwordMin": "Le mot de passe doit contenir au moins 6 caractères",
    "auth.nameMin": "Le nom doit contenir au moins 2 caractères",
    "auth.nameMax": "Le nom est trop long",
    "auth.passwordMismatch": "Les mots de passe ne correspondent pas",
    "auth.noAccount": "Pas encore de compte ?",
    "auth.hasAccount": "Déjà un compte ?",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.solutions": "Solutions",
    "nav.features": "Features",
    "nav.contact": "Contact",
    "nav.login": "Login",
    "nav.start": "Get Started",
    "nav.dashboard": "Dashboard",
    
    // Hero
    "hero.title1": "Your",
    "hero.title2": "Intelligent",
    "hero.title3": "Archivist",
    "hero.description": "From your pocket to the Nation — The first multi-scale intelligent archiving platform. Digitize, organize and secure your documents with AI.",
    "hero.cta.primary": "Try for Free",
    "hero.cta.secondary": "Watch Demo",
    
    // Services
    "services.title1": "Complete",
    "services.title2": "Solutions",
    "services.description": "DIGITALIUM transforms document management from citizens to institutions.",
    "services.scan.title": "Smart Scan",
    "services.scan.description": "Digitize your documents with our advanced OCR technology.",
    "services.ai.title": "AI Assistant",
    "services.ai.description": "An intelligent archivist available 24/7.",
    "services.security.title": "Sovereign Security",
    "services.security.description": "Bank-level encryption, local hosting.",
    "services.persona.title": "Multi-Persona",
    "services.persona.description": "Interface adapted to each user profile.",
    "services.offline.title": "Offline Mode",
    "services.offline.description": "Work without connection, automatic sync.",
    "services.workflow.title": "Workflows",
    "services.workflow.description": "Automate your document processes.",
    "services.learnMore": "Learn more",
    "services.cta": "Discover all our services",
    
    // Solutions
    "solutions.title1": "A Solution",
    "solutions.title2": "Adapted",
    "solutions.description": "From individuals to public administration, DIGITALIUM adapts to your scale.",
    "solutions.popular": "Most popular",
    "solutions.choose": "Choose",
    "solutions.citizen.title": "Citizens",
    "solutions.citizen.subtitle": "DIGITALIUM Personal",
    "solutions.citizen.description": "Organize all your administrative documents easily.",
    "solutions.citizen.price": "Free",
    "solutions.citizen.f1": "ID, passport, diplomas",
    "solutions.citizen.f2": "Expiration reminders",
    "solutions.citizen.f3": "100 free docs",
    "solutions.business.title": "Businesses",
    "solutions.business.subtitle": "DIGITALIUM Business",
    "solutions.business.description": "Digitize your document management.",
    "solutions.business.price": "15,000 XAF/month",
    "solutions.business.f1": "Multi-users",
    "solutions.business.f2": "Automated workflows",
    "solutions.business.f3": "API & Integrations",
    "solutions.institution.title": "Institutions",
    "solutions.institution.subtitle": "DIGITALIUM Sovereign",
    "solutions.institution.description": "Sovereign solution for administrations.",
    "solutions.institution.price": "On quote",
    "solutions.institution.f1": "Gabon hosting",
    "solutions.institution.f2": "24/7 Support",
    "solutions.institution.f3": "Training included",
    "solutions.trust": "They trust us",
    
    // Features
    "features.title1": "AI that",
    "features.title2": "Works",
    "features.title3": "for You",
    "features.description": "A smooth and intuitive document management experience.",
    "features.assistant.title": "AI Assistant",
    "features.assistant.description": "Talk naturally to your AI archivist to organize your documents.",
    "features.scan.title": "Smart Scan",
    "features.scan.description": "Scan with your smartphone, AI automatically extracts text.",
    "features.organization.title": "Auto Organization",
    "features.organization.description": "AI automatically classifies your documents by category and date.",
    "features.alerts.title": "Smart Alerts",
    "features.alerts.description": "Get notified before your important documents expire.",
    "features.share.title": "Secure Sharing",
    "features.share.description": "Share documents with full permission control.",
    "features.encryption.title": "E2E Encryption",
    "features.encryption.description": "Your sensitive documents encrypted, even we cannot read them.",
    "features.demo.title": "See AI in Action",
    "features.demo.request": "Prepare a folder for my France visa application",
    "features.demo.response": "I found 5 documents in your archives. I'm creating the 'France Visa 2024' folder with: passport, bank statements (last 3 months), employer certificate...",
    
    // Contact
    "contact.title1": "Let's Talk About Your",
    "contact.title2": "Project",
    "contact.description": "Our team is available to answer all your questions and support you in your digital transformation.",
    "contact.address": "Address",
    "contact.address.value": "Libreville, Gabon",
    "contact.phone": "Phone",
    "contact.phone.value": "+241 XX XX XX XX",
    "contact.email": "Email",
    "contact.email.value": "contact@digitalium.ga",
    "contact.hours": "Hours",
    "contact.hours.value": "Mon-Fri: 8am-6pm",
    "contact.form.name": "Your name *",
    "contact.form.email": "Your email *",
    "contact.form.subject": "Subject",
    "contact.form.message": "Your message *",
    "contact.form.submit": "Send message",
    "contact.form.sending": "Sending...",
    "contact.form.success.title": "Message Sent!",
    "contact.form.success.description": "Our team will respond within 24h.",
    "contact.form.new": "Send a new message",
    "contact.form.required": "Required fields",
    "contact.form.required.description": "Please fill in all required fields.",
    "contact.form.error": "Error",
    "contact.form.error.description": "An error occurred. Please try again.",
    "contact.map": "Map",
    "contact.callNow": "Call us now",
    
    // FAQ
    "faq.badge": "FAQ",
    "faq.title1": "Frequently",
    "faq.title2": "Asked Questions",
    "faq.description": "Everything you need to know about DIGITALIUM and how it can transform your document management.",
    "faq.more": "Have more questions?",
    "faq.contact": "Contact our team",
    "faq.q1": "What is DIGITALIUM and how does it work?",
    "faq.a1": "DIGITALIUM is the first multi-scale intelligent archiving platform that combines generative AI and institutional rigor. Our archivist assistant automatically analyzes your documents, classifies them, extracts metadata, and helps you find them instantly through advanced semantic search.",
    "faq.q2": "Are my documents secure on DIGITALIUM?",
    "faq.a2": "Absolutely. We use AES-256 encryption for data at rest and TLS 1.3 for data in transit. For institutions, we offer an end-to-end encryption option with sovereign hosting in Gabon. All actions are tracked in an immutable audit log.",
    "faq.q3": "What types of documents can I scan and archive?",
    "faq.a3": "DIGITALIUM accepts all types of documents: IDs, passports, diplomas, invoices, contracts, notarial deeds, bank statements, medical certificates, and more. Our AI automatically detects the document type and organizes it in the right category.",
    "faq.q4": "Can I use DIGITALIUM offline?",
    "faq.a4": "Yes! DIGITALIUM works in offline-first mode. You can scan, organize, and view your documents even without an internet connection. Everything syncs automatically as soon as you regain connection.",
    "faq.q5": "How does pricing work?",
    "faq.a5": "We offer a free tier with 1 GB of storage and 100 documents. The Personal plan at 2,000 XAF/month includes 10 GB and unlimited documents. The Family plan at 5,000 XAF/month allows up to 5 users. For businesses and institutions, contact us for a custom quote.",
    "faq.q6": "Can AI really understand my documents?",
    "faq.a6": "Yes, our AI uses state-of-the-art models to visually and textually analyze your documents. It can extract structured data (dates, amounts, names), detect expired documents, and even suggest actions like creating thematic folders.",
    "faq.q7": "How does DIGITALIUM help businesses?",
    "faq.a7": "For businesses, DIGITALIUM offers automated workflows (invoice validation, employee onboarding), multi-user management with RBAC, analytics dashboards, API integration, and compliance reports. The average ROI observed is 253% with a 15-day payback period.",
    "faq.q8": "Is DIGITALIUM available for public administrations?",
    "faq.a8": "Yes, we offer an Institutional plan specially designed for city halls, ministries, and administrations. It includes on-premise deployment, sovereign hosting in Gabon, GDPR and Gabonese law compliance, and dedicated 24/7 support.",
    
    // Footer
    "footer.description": "The intelligent archivist that transforms your document management. Made in Gabon 🇬🇦",
    "footer.copyright": "All rights reserved.",
    "footer.poweredBy": "Powered by",
    "footer.product": "Product",
    "footer.product.features": "Features",
    "footer.product.solutions": "Solutions",
    "footer.product.pricing": "Pricing",
    "footer.product.security": "Security",
    "footer.company": "Company",
    "footer.company.about": "About",
    "footer.company.careers": "Careers",
    "footer.company.partners": "Partners",
    "footer.company.blog": "Blog",
    "footer.resources": "Resources",
    "footer.resources.docs": "Documentation",
    "footer.resources.api": "API",
    "footer.resources.support": "Support",
    "footer.resources.status": "Status",
    "footer.legal": "Legal",
    "footer.legal.privacy": "Privacy",
    "footer.legal.terms": "Terms",
    "footer.legal.cookies": "Cookies",
    "footer.legal.licenses": "Licenses",
    
    // Auth
    "auth.title": "DIGITALIUM",
    "auth.subtitle": "Access your personal space",
    "auth.login": "Login",
    "auth.signup": "Sign up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm password",
    "auth.fullName": "Full name",
    "auth.emailPlaceholder": "you@example.com",
    "auth.passwordPlaceholder": "••••••••",
    "auth.namePlaceholder": "John Doe",
    "auth.loginButton": "Sign in",
    "auth.signupButton": "Create account",
    "auth.logging": "Signing in...",
    "auth.creating": "Creating...",
    "auth.loginError": "Login error",
    "auth.loginErrorMsg": "Incorrect email or password.",
    "auth.error": "Error",
    "auth.accountExists": "Account exists",
    "auth.accountExistsMsg": "An account already exists with this email. Please sign in instead.",
    "auth.signupError": "Signup error",
    "auth.loginSuccess": "Login successful",
    "auth.loginSuccessMsg": "Welcome to DIGITALIUM!",
    "auth.signupSuccess": "Account created!",
    "auth.signupSuccessMsg": "Welcome to DIGITALIUM!",
    "auth.invalidEmail": "Invalid email",
    "auth.passwordMin": "Password must be at least 6 characters",
    "auth.nameMin": "Name must be at least 2 characters",
    "auth.nameMax": "Name is too long",
    "auth.passwordMismatch": "Passwords do not match",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "fr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.fr] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
